### ISSUE TITLE
Spacing issues in Mobile

### ISSUE THREAD

**Issue by shelbyboyd** [emilylavinskas/portfolio-old#3]
Mobile- android internet explorer- hamburger toggle unnecessary and sits over top of menu items. "Creative Thinker" gets cut off and your name sits over top of menu items.

**Comment by jamie-smith8** [comment]
in other words.... here's a photo. 
![img_1172](https://cloud.githubusercontent.com/assets/6372772/10367713/f901576e-6d9f-11e5-9a25-96e16f66f238.PNG)

**Comment by devonash** [comment]
Similar happenings in (safari 7) on smaller screens

![screen shot 2015-10-08 at 9 38 25 am](https://cloud.githubusercontent.com/assets/6373210/10367870/c2319446-6da0-11e5-9a33-063b210c2970.png)

**Comment by marisabivi** [comment]
Same for Opera Mini. 
![img_9438](https://cloud.githubusercontent.com/assets/6371052/10368382/eee47178-6da2-11e5-9370-cabf7521e972.PNG)
